### ISSUE TITLE
[Bug]: Missing link to "Terraform Style Guide" in codex

### ISSUE THREAD

**Issue by jtracey93** [Azure/terraform-azure-modules#19]
### Module Name

N/A

### Description

Missing link to "Terraform Style Guide" in codex:

![image](https://user-images.githubusercontent.com/41163455/223671947-a4772ec6-6ca5-4d3d-b6eb-227a0ae9fefb.png)

> Src: https://github.com/Azure/terraform-azure-modules/blob/main/codex/general_rules.md

### Code

```HCL
N/A
```

**Comment by lonegunmanb** [comment]
Thanks @jtracey93 for opening this issue, that's because HashiCorp hasn't published this document yet so we cannot obtain a link. We'll update the document once HashiCorp has made that document public.
